#!/usr/bin/env node
// Builds dist/tokens.css from tokens/design-tokens.json.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const t = JSON.parse(readFileSync('tokens/design-tokens.json', 'utf8'));
const ext = n => n.$extensions['com.mhr.pf'];

const collect = (node, acc = []) => {
  if (node && typeof node === 'object') {
    if (node.$type) acc.push(node);
    else Object.values(node).forEach(v => collect(v, acc));
  }
  return acc;
};

const decl = (name, value, comment) =>
  `  ${name}: ${value};${comment ? ` /* ${comment} */` : ''}`;

// --- primitives ---
const primitives = [...collect(t.color.base), ...collect(t.color.theme)]
  .map(n => decl(ext(n).cssVar, n.$value, ext(n).figmaName));

// --- scalars ---
const scalar = (group, label) => {
  const rows = collect(group).map(n => decl(ext(n).cssVar, Array.isArray(n.$value) ? n.$value.join(', ') : n.$value));
  return rows.length ? [`\n  /* ${label} */`, ...rows] : [];
};

const shadows = collect(t.shadow).map(n => decl(ext(n).cssVar, ext(n).css, ext(n).figmaName));
const gradients = collect(t.gradient).map(n => decl(ext(n).cssVar, n.$value, ext(n).figmaName));

// --- semantic, per mode ---
const semantic = collect(t.color.semantic);
const semanticFor = mode => semantic.map(n => {
  const e = ext(n);
  const ref = e.cssRef[mode];
  const raw = e.modes[mode];
  const value = ref ? `var(${ref})` : raw;
  return decl(e.cssVar, value, ref ? null : 'literal');
});

const light = semanticFor('light');
const dark = semanticFor('dark');

const header = `/* People First Design System — design tokens
 * GENERATED by scripts/build-css.mjs. Do not edit by hand.
 * Source: Figma file aRWjBnTvdLiG50xtwodGwH (People First Design System)
 *
 * Dark mode: set data-theme="dark" on <html>, or leave it unset and the
 * system preference applies. data-theme="light" pins light mode.
 */\n`;

const css = [
  header,
  ':root {',
  '  color-scheme: light dark;',
  '',
  '  /* ---- Primitive colours (Colours Primitive) ---- */',
  ...primitives,
  ...scalar(t.font, 'Font families'),
  ...scalar(t.fontSize, 'Font sizes'),
  ...scalar(t.fontWeight, 'Font weights'),
  ...scalar(t.space, 'Spacing'),
  ...scalar(t.radius, 'Radius'),
  ...scalar(t.iconSize, 'Icon sizes'),
  '\n  /* Shadows */',
  ...shadows,
  '\n  /* Gradients */',
  ...gradients,
  '',
  '  /* ---- Semantic colours — Lightmode ---- */',
  ...light,
  '}',
  '',
  '/* ---- Semantic colours — Darkmode (explicit) ---- */',
  '/*',
  ' * `color-scheme` has to move with the attribute, not just with the OS.',
  ' *',
  ' * `:root { color-scheme: light dark }` tells the browser to follow the SYSTEM preference',
  ' * for everything it paints itself — the default text colour, form controls, scrollbars.',
  ' * `data-theme="dark"` swapped all 111 tokens and left that alone, so on a light OS the',
  ' * page went dark and the browser went on painting inherited text BLACK. Measured: 69 of',
  ' * the 160 component classes rendered a different colour depending on WHICH WAY dark mode',
  ' * was turned on, every one of them a class that inherits its text colour rather than',
  ' * stating one. Reported from a phone as the filter chips looking wrong in dark mode.',
  ' *',
  ' * Every dark screenshot in this repo is taken with the attribute (scripts/shoot.mjs sets',
  ' * data-theme), so this is the path the eye actually sees.',
  ' */',
  ':root[data-theme="dark"] {',
  '  color-scheme: dark;',
  ...dark,
  '}',
  '',
  '/* The same for a page pinning light mode on a dark OS. */',
  ':root[data-theme="light"] {',
  '  color-scheme: light;',
  '}',
  '',
  '/* ---- Semantic colours — Darkmode (system preference) ---- */',
  '@media (prefers-color-scheme: dark) {',
  '  :root:not([data-theme="light"]) {',
  ...dark.map(l => '  ' + l),
  '  }',
  '}',
  ''
].join('\n');

mkdirSync('dist', { recursive: true });
writeFileSync('dist/tokens.css', css);

const varCount = (css.match(/^\s+--pf-/gm) || []).length;
console.log(`dist/tokens.css written — ${varCount} declarations, ${semantic.length} semantic tokens x 2 modes`);
