#!/usr/bin/env node
// Builds tokens/design-tokens.json (W3C DTCG) from the raw Figma extract in tokens/_raw/.
// Regenerate by re-extracting from Figma into tokens/_raw/, then re-running this.
import { readFileSync, writeFileSync } from 'node:fs';

const RAW = 'tokens/_raw';
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// Figma group -> token group. Keeps generated names short without inventing structure.
const GROUP = {
  'Background': 'bg', 'Border': 'border', 'Text': 'text', 'Icons': 'icon',
  'Charts': 'chart', 'Tags': 'tag', 'Table': 'table', 'Buttons': 'button',
  'Filter menu': 'filter-menu', 'Org cards': 'org-card', 'Progress bar': 'progress-bar'
};
const SUBGROUP = { 'Fills': 'fill', 'Borders': 'border', 'Content': 'content' };

// Strip a redundant prefix the Figma name repeats from its own group.
const stripRepeat = (group, leaf) => {
  const m = leaf.match(/^(Icon|Border|Chart)\s*-?\s*(.+)$/i);
  return m ? m[2] : leaf;
};

function semanticPath(figmaName) {
  const parts = figmaName.split('/').map(p => p.trim());
  const group = GROUP[parts[0]] ?? slug(parts[0]);
  let sub = null, leaf;
  if (parts.length === 3) { sub = SUBGROUP[parts[1]] ?? slug(parts[1]); leaf = parts[2]; }
  else leaf = parts[1];
  leaf = slug(stripRepeat(parts[0], leaf));
  // Org cards/Fills/* reads better without the 'fill' segment.
  if (group === 'org-card') sub = null;
  const segs = sub ? [group, sub, leaf] : [group, leaf];
  return { dtcg: ['color', 'semantic', ...segs].join('.'), css: '--pf-' + segs.join('-') };
}

function primitivePath(figmaName) {
  const [grp, leaf] = figmaName.split('/').map(p => p.trim());
  const g = grp === 'Base colours' ? 'base' : slug(grp);
  return { dtcg: `color.${g}.${slug(leaf)}`, css: `--pf-${g}-${slug(leaf)}` };
}

// ---- load raw ----
const tsv = f => readFileSync(`${RAW}/${f}`, 'utf8').trim().split('\n').map(l => l.split('\t'));
const primitives = tsv('primitives.tsv');
const semantic = tsv('semantic.tsv');
const other = JSON.parse(readFileSync(`${RAW}/other.json`, 'utf8'));

// ---- index every colour so aliases can resolve ----
const index = new Map(); // figmaName -> {dtcg, css}
for (const [name] of primitives) index.set(name, primitivePath(name));
for (const [name] of semantic) index.set(name, semanticPath(name));

const unresolved = [];
function refOf(raw, from) {
  if (!raw.startsWith('@')) return null;
  const target = raw.slice(1);
  const hit = index.get(target);
  if (!hit) { unresolved.push({ from, target }); return null; }
  return hit;
}

const out = {
  $schema: 'https://design-tokens.org/schema.json',
  $description:
    'People First Design System — extracted from Figma file aRWjBnTvdLiG50xtwodGwH. ' +
    'Semantic colours carry a Darkmode value under $extensions."com.mhr.pf".modes.dark. ' +
    'Generated by scripts/build-tokens.mjs — do not hand-edit.',
  color: { base: {}, theme: {}, semantic: {} },
  dimension: {}, radius: {}, space: {}, iconSize: {},
  font: {}, fontSize: {}, fontWeight: {}, shadow: {}, grid: {}, gradient: {}
};

const put = (root, path, value) => {
  const segs = path.split('.');
  let node = root;
  for (const s of segs.slice(0, -1)) node = (node[s] ??= {});
  node[segs.at(-1)] = value;
};

// ---- primitives ----
for (const [name, hex] of primitives) {
  const p = index.get(name);
  put(out, p.dtcg, {
    $type: 'color', $value: hex,
    $extensions: { 'com.mhr.pf': { figmaName: name, cssVar: p.css, tier: 'primitive' } }
  });
}

// ---- semantic (light = $value, dark under $extensions) ----
for (const [name, light, dark, scopes] of semantic) {
  const p = index.get(name);
  const lr = refOf(light, name), dr = refOf(dark, name);
  put(out, p.dtcg, {
    $type: 'color',
    $value: lr ? `{${lr.dtcg}}` : light,
    $extensions: {
      'com.mhr.pf': {
        figmaName: name, cssVar: p.css, tier: 'semantic',
        scopes: scopes ? scopes.split('+') : [],
        modes: {
          light: lr ? `{${lr.dtcg}}` : light,
          dark: dr ? `{${dr.dtcg}}` : dark
        },
        cssRef: { light: lr ? lr.css : null, dark: dr ? dr.css : null }
      }
    }
  });
}

// ---- dimensions ----
for (const d of other.dimensions) {
  const leaf = slug(d.name.split('/').pop().replace(/^(radius|sizing)-/, ''));
  const group = d.name.startsWith('Radius/') ? 'radius'
    : d.name.startsWith('Spacing/') ? 'space' : 'iconSize';
  const key = group === 'iconSize' ? slug(d.name.replace(/^Icon-size-/, '')) : leaf;
  const cssGroup = group === 'iconSize' ? 'icon-size' : group;
  out[group][key] = {
    $type: 'dimension', $value: `${d.value}px`,
    $extensions: { 'com.mhr.pf': { figmaName: d.name, cssVar: `--pf-${cssGroup}-${key}`, raw: d.value, scopes: [d.scopes] } }
  };
}

// ---- typography ----
for (const t of other.typography) {
  if (t.name === 'Body' || t.name === 'Headings') {
    const k = t.name === 'Body' ? 'body' : 'heading';
    out.font[k] = { $type: 'fontFamily', $value: [t.value, 'system-ui', 'sans-serif'],
      $extensions: { 'com.mhr.pf': { figmaName: t.name, cssVar: `--pf-font-${k}` } } };
  } else if (t.name.startsWith('Size/')) {
    const k = slug(t.name.slice(5));
    out.fontSize[k] = { $type: 'dimension', $value: `${t.value}px`,
      $extensions: { 'com.mhr.pf': { figmaName: t.name, cssVar: `--pf-font-size-${k}`, raw: t.value } } };
  } else if (t.name.startsWith('Weight/')) {
    const k = slug(t.name.slice(7));
    const num = t.value === 'SemiBold' ? 600 : 400;
    out.fontWeight[k] = { $type: 'fontWeight', $value: num,
      $extensions: { 'com.mhr.pf': { figmaName: t.name, cssVar: `--pf-font-weight-${k}`, figmaStyle: t.value } } };
  }
}

// ---- shadows ----
for (const e of other.effectStyles) {
  const k = slug(e.name);
  const a = e.alpha < 1 ? Math.round(e.alpha * 255).toString(16).padStart(2, '0') : '';
  out.shadow[k] = {
    $type: 'shadow',
    $value: { color: e.color + a, offsetX: `${e.x}px`, offsetY: `${e.y}px`, blur: `${e.radius}px`, spread: `${e.spread}px` },
    $extensions: { 'com.mhr.pf': { figmaName: e.name, cssVar: `--pf-shadow-${k}`,
      css: `${e.x}px ${e.y}px ${e.radius}px ${e.spread}px ${e.color}${a}` } }
  };
}

// ---- grids ----
for (const g of other.gridStyles) {
  const k = slug(g.name);
  out.grid[k] = { $type: 'other', $value: g,
    $extensions: { 'com.mhr.pf': { figmaName: g.name, width: parseInt(g.name, 10) } } };
}

// ---- gradients ----
for (const g of other.gradients) {
  const k = slug(g.name);
  const css = `linear-gradient(90deg, ${g.stops.map(s => `${s.color} ${(s.pos * 100).toFixed(1)}%`).join(', ')})`;
  out.gradient[k] = { $type: 'other', $value: css,
    $extensions: { 'com.mhr.pf': { figmaName: g.name, cssVar: `--pf-gradient-${k}`, stops: g.stops } } };
}

writeFileSync('tokens/design-tokens.json', JSON.stringify(out, null, 2) + '\n');

const count = o => { let n = 0; const walk = x => { if (x && typeof x === 'object') { if (x.$type) n++; else Object.values(x).forEach(walk); } }; walk(o); return n; };
console.log(`design-tokens.json written — ${count(out)} tokens`);
if (unresolved.length) { console.error('UNRESOLVED ALIASES:', unresolved); process.exit(1); }
console.log('all aliases resolved');
